[package]
name = "motorcillo-rs"
version = "0.1.0"
authors = ["Ferran Basora <fcsonline@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.1"
rocket_contrib = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = "0.4"

